version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: wordpress_nginx
    restart: always
    ports:
      - "3232:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app_network
    depends_on:
      - api
  api:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - api:/backup
    networks:
      - app_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: apidb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      DB_HOST: host
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: apidb
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    container_name: db

volumes:
  mysql_data:
  api:
    driver: local
    driver_opts:
        type: none
        o: bind
        device: ~/

networks:
  app_network:
    driver: bridge